package errors

import (
	"google.golang.org/grpc/codes"
)

var (
	ErrInvalidToken           = NewError(codes.Unauthenticated, "invalid token")
	ErrTokenExpired           = NewError(codes.Unauthenticated, "token expired")
	ErrTokenRevoked           = NewError(codes.Unauthenticated, "token revoked")
	ErrTokenGeneration        = NewError(codes.Internal, "failed to generate tokens")
	ErrAccessTokenMismatch    = NewError(codes.Unauthenticated, "access token mismatch")
	ErrRefreshTokenInvalid    = NewError(codes.Unauthenticated, "refresh token invalid")
	ErrUnauthenticated        = NewError(codes.Unauthenticated, "unauthenticated")
	ErrMissingToken           = NewError(codes.InvalidArgument, "missing token")
	ErrUserAlreadyExists      = NewError(codes.AlreadyExists, "user already exists")
	ErrUserNotFound           = NewError(codes.NotFound, "user not found")
	ErrUsernameTaken          = NewError(codes.AlreadyExists, "username taken")
	ErrEmailTaken             = NewError(codes.AlreadyExists, "email taken")
	ErrEmailNotVerified       = NewError(codes.FailedPrecondition, "email not verified")
	ErrAccountLocked          = NewError(codes.PermissionDenied, "account is locked")
	ErrAccountDisabled        = NewError(codes.PermissionDenied, "account disabled")
	ErrInvalidCredentials     = NewError(codes.Unauthenticated, "invalid credentials")
	ErrPasswordMismatch       = NewError(codes.InvalidArgument, "password mismatch")
	ErrPasswordTooWeak        = NewError(codes.InvalidArgument, "password too weak")
	ErrSessionNotFound        = NewError(codes.NotFound, "session not found")
	ErrLogoutFailed           = NewError(codes.NotFound, "logout failed")
	ErrPermissionDenied       = NewError(codes.PermissionDenied, "permission denied")
	ErrUnauthorizedOperation  = NewError(codes.PermissionDenied, "unauthorized operation")
	ErrInsufficientPrivileges = NewError(codes.PermissionDenied, "insufficient privileges")
	ErrValidationFailed       = NewError(codes.InvalidArgument, "validation failed")
	ErrMissingRequiredFields  = NewError(codes.InvalidArgument, "missing required fields")
	ErrInvalidEmailFormat     = NewError(codes.InvalidArgument, "invalid email format")
	ErrInvalidUsernameFormat  = NewError(codes.InvalidArgument, "invalid username format")
	ErrInvalidRequestFormat   = NewError(codes.InvalidArgument, "invalid request format")
	ErrTooManyRequests        = NewError(codes.ResourceExhausted, "too many requests")
	ErrRateLimitExceeded      = NewError(codes.ResourceExhausted, "rate limit exceeded")
	ErrServiceUnavailable     = NewError(codes.Unavailable, "service unavailable")
	ErrDeadlineExceeded       = NewError(codes.DeadlineExceeded, "deadline exceeded")
	ErrInternalServer         = NewError(codes.Internal, "internal server error")
	ErrDatabaseFailure        = NewError(codes.Internal, "database failure")
	ErrCacheUnavailable       = NewError(codes.Unavailable, "cache unavailable")
	ErrDependencyUnavailable  = NewError(codes.Unavailable, "dependency unavailable")
	ErrOperationTimedOut      = NewError(codes.DeadlineExceeded, "operation timed out")
)
