// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: hello_service/hello_service.proto

package hello_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_hello_service_hello_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_service_hello_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_hello_service_hello_service_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_hello_service_hello_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_service_hello_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_hello_service_hello_service_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_hello_service_hello_service_proto protoreflect.FileDescriptor

const file_hello_service_hello_service_proto_rawDesc = "" +
	"\n" +
	"!hello_service/hello_service.proto\x12\rhello_service\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"#\n" +
	"\rHelloResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2U\n" +
	"\fHelloService\x12E\n" +
	"\bSayHello\x12\x1b.hello_service.HelloRequest\x1a\x1c.hello_service.HelloResponseB<Z:github.com/vwency/microservices_golang/proto/hello_serviceb\x06proto3"

var (
	file_hello_service_hello_service_proto_rawDescOnce sync.Once
	file_hello_service_hello_service_proto_rawDescData []byte
)

func file_hello_service_hello_service_proto_rawDescGZIP() []byte {
	file_hello_service_hello_service_proto_rawDescOnce.Do(func() {
		file_hello_service_hello_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hello_service_hello_service_proto_rawDesc), len(file_hello_service_hello_service_proto_rawDesc)))
	})
	return file_hello_service_hello_service_proto_rawDescData
}

var file_hello_service_hello_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hello_service_hello_service_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: hello_service.HelloRequest
	(*HelloResponse)(nil), // 1: hello_service.HelloResponse
}
var file_hello_service_hello_service_proto_depIdxs = []int32{
	0, // 0: hello_service.HelloService.SayHello:input_type -> hello_service.HelloRequest
	1, // 1: hello_service.HelloService.SayHello:output_type -> hello_service.HelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_service_hello_service_proto_init() }
func file_hello_service_hello_service_proto_init() {
	if File_hello_service_hello_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_service_hello_service_proto_rawDesc), len(file_hello_service_hello_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_service_hello_service_proto_goTypes,
		DependencyIndexes: file_hello_service_hello_service_proto_depIdxs,
		MessageInfos:      file_hello_service_hello_service_proto_msgTypes,
	}.Build()
	File_hello_service_hello_service_proto = out.File
	file_hello_service_hello_service_proto_goTypes = nil
	file_hello_service_hello_service_proto_depIdxs = nil
}
