app:
    env: dev
    port: "50056"
    log_level: debug
    service_name: "gateway"

auth_service:
  url: "localhost:50051"

database_service:
  url: "localhost:50052" 

jwt:
  secret: "your_secret_key"
  access_token_ttl: "3600s" 
  refresh_token_ttl: "7200s" 
