services:
  postgres:
    build:
      context: ./deploy/database
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pure
      POSTGRES_USER: postgres
      PGPORT: 5432
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      app_network:
        ipv4_address: 192.168.1.2

  database_service:
    build:
      context: .
      dockerfile: ./deploy/database_service/Dockerfile
    container_name: database_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 50052
      LOG_LEVEL: debug
      DATABASE_URL: "postgres://postgres:password@postgres:5432/pure?sslmode=disable"
    ports:
      - "50052:50052"
    networks:
      app_network:
        ipv4_address: 192.168.1.3

  auth_service:
    build:
      context: .
      dockerfile: ./deploy/auth_service/Dockerfile
    container_name: auth_service
    depends_on:
      database_service:
        condition: service_started
    environment:
      PORT: 50056
      LOG_LEVEL: debug
      AUTH_SECRET_KEY: "supersecretkey"
      TOKEN_TTL: 3600
    ports:
      - "50056:50056"
    networks:
      app_network:
        ipv4_address: 192.168.1.4

  gateway:
    build:
      context: .
      dockerfile: ./deploy/gateway/Dockerfile
    container_name: gateway
    depends_on:
      auth_service:
        condition: service_started
      database_service:
        condition: service_started
    environment:
      PORT: 50051
      LOG_LEVEL: debug
      AUTH_SERVICE_URL: "auth_service:50056"
    ports:
      - "50058:50058"
    networks:
      app_network:
        ipv4_address: 192.168.1.5

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
