version: '3'

tasks:
    run-service1:
        desc: Run service1
        cmds:
          - go run ./cmd/service1

    proto-generate:
        desc: Generate gRPC code from proto
        cmds:
          - protoc --go_out=proto/service1 --go-grpc_out=proto/service1 \ --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative \ proto/service1.proto
