version: "3"

tasks:
  run-hello_service:
    desc: Run hello_service
    cmds:
      - go run ./cmd/hello_service

  proto-generate:
    desc: Generate gRPC code from proto
    cmds:
      - protoc --proto_path=../proto --go_out=./proto --go-grpc_out=./proto --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative ../proto/hello_service/hello_service.proto
