// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: jwt_service/jwt_service.proto

package jwt_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *string                `protobuf:"bytes,1,opt,name=secret,proto3,oneof" json:"secret,omitempty"` // Сделали опциональным
	Payload       map[string]string      `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // Время жизни токена в секундах (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenRequest) Reset() {
	*x = GenerateTokenRequest{}
	mi := &file_jwt_service_jwt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenRequest) ProtoMessage() {}

func (x *GenerateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_service_jwt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateTokenRequest) Descriptor() ([]byte, []int) {
	return file_jwt_service_jwt_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTokenRequest) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

func (x *GenerateTokenRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GenerateTokenRequest) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type GenerateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp времени истечения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenResponse) Reset() {
	*x = GenerateTokenResponse{}
	mi := &file_jwt_service_jwt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenResponse) ProtoMessage() {}

func (x *GenerateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_service_jwt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateTokenResponse) Descriptor() ([]byte, []int) {
	return file_jwt_service_jwt_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Secret        *string                `protobuf:"bytes,2,opt,name=secret,proto3,oneof" json:"secret,omitempty"` // Сделали опциональным
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_jwt_service_jwt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_service_jwt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_jwt_service_jwt_service_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenRequest) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Добавлено поле с временем истечения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_jwt_service_jwt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_service_jwt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_jwt_service_jwt_service_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ValidateTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidateTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_jwt_service_jwt_service_proto protoreflect.FileDescriptor

const file_jwt_service_jwt_service_proto_rawDesc = "" +
	"\n" +
	"\x1djwt_service/jwt_service.proto\x12\vjwt_service\"\xe3\x01\n" +
	"\x14GenerateTokenRequest\x12\x1b\n" +
	"\x06secret\x18\x01 \x01(\tH\x00R\x06secret\x88\x01\x01\x12H\n" +
	"\apayload\x18\x02 \x03(\v2..jwt_service.GenerateTokenRequest.PayloadEntryR\apayload\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_secret\"L\n" +
	"\x15GenerateTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"T\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\x06secret\x18\x02 \x01(\tH\x00R\x06secret\x88\x01\x01B\t\n" +
	"\a_secret\"\x82\x02\n" +
	"\x15ValidateTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12I\n" +
	"\apayload\x18\x03 \x03(\v2/.jwt_service.ValidateTokenResponse.PayloadEntryR\apayload\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xbc\x01\n" +
	"\n" +
	"JwtService\x12V\n" +
	"\rGenerateToken\x12!.jwt_service.GenerateTokenRequest\x1a\".jwt_service.GenerateTokenResponse\x12V\n" +
	"\rValidateToken\x12!.jwt_service.ValidateTokenRequest\x1a\".jwt_service.ValidateTokenResponseB:Z8github.com/vwency/microservices_golang/proto/jwt_serviceb\x06proto3"

var (
	file_jwt_service_jwt_service_proto_rawDescOnce sync.Once
	file_jwt_service_jwt_service_proto_rawDescData []byte
)

func file_jwt_service_jwt_service_proto_rawDescGZIP() []byte {
	file_jwt_service_jwt_service_proto_rawDescOnce.Do(func() {
		file_jwt_service_jwt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jwt_service_jwt_service_proto_rawDesc), len(file_jwt_service_jwt_service_proto_rawDesc)))
	})
	return file_jwt_service_jwt_service_proto_rawDescData
}

var file_jwt_service_jwt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_jwt_service_jwt_service_proto_goTypes = []any{
	(*GenerateTokenRequest)(nil),  // 0: jwt_service.GenerateTokenRequest
	(*GenerateTokenResponse)(nil), // 1: jwt_service.GenerateTokenResponse
	(*ValidateTokenRequest)(nil),  // 2: jwt_service.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 3: jwt_service.ValidateTokenResponse
	nil,                           // 4: jwt_service.GenerateTokenRequest.PayloadEntry
	nil,                           // 5: jwt_service.ValidateTokenResponse.PayloadEntry
}
var file_jwt_service_jwt_service_proto_depIdxs = []int32{
	4, // 0: jwt_service.GenerateTokenRequest.payload:type_name -> jwt_service.GenerateTokenRequest.PayloadEntry
	5, // 1: jwt_service.ValidateTokenResponse.payload:type_name -> jwt_service.ValidateTokenResponse.PayloadEntry
	0, // 2: jwt_service.JwtService.GenerateToken:input_type -> jwt_service.GenerateTokenRequest
	2, // 3: jwt_service.JwtService.ValidateToken:input_type -> jwt_service.ValidateTokenRequest
	1, // 4: jwt_service.JwtService.GenerateToken:output_type -> jwt_service.GenerateTokenResponse
	3, // 5: jwt_service.JwtService.ValidateToken:output_type -> jwt_service.ValidateTokenResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jwt_service_jwt_service_proto_init() }
func file_jwt_service_jwt_service_proto_init() {
	if File_jwt_service_jwt_service_proto != nil {
		return
	}
	file_jwt_service_jwt_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_jwt_service_jwt_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jwt_service_jwt_service_proto_rawDesc), len(file_jwt_service_jwt_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwt_service_jwt_service_proto_goTypes,
		DependencyIndexes: file_jwt_service_jwt_service_proto_depIdxs,
		MessageInfos:      file_jwt_service_jwt_service_proto_msgTypes,
	}.Build()
	File_jwt_service_jwt_service_proto = out.File
	file_jwt_service_jwt_service_proto_goTypes = nil
	file_jwt_service_jwt_service_proto_depIdxs = nil
}
