syntax = "proto3";

package jwt_service;

option go_package = "github.com/vwency/microservices_golang/proto/jwt_service";

service JwtService {
  rpc GenerateToken (GenerateTokenRequest) returns (GenerateTokenResponse);
  rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenResponse);
}

message GenerateTokenRequest {
  optional string secret = 1;
  map<string, string> payload = 2;
  int64 expires_in = 3;
}

message GenerateTokenResponse {
  string token = 1;
  int64 expires_at = 2;
}

message ValidateTokenRequest {
  string token = 1;
  optional string secret = 2;
}

message ValidateTokenResponse {
  string user_id = 1;
  bool valid = 2;
  map<string, string> payload = 3;
  string error = 4;
  int64 expires_at = 5;
}
