jwt:
  secret: "your-secret-key"
  access_token_ttl: 15m
  refresh_token_ttl: 24h

app:
  env: dev
  port: "50056"
  log_level: debug
  service_name: "auth_service"


auth_service:
  url: "localhost:50056"

database_service:
  url: "database_service:50052"
