// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: database_init/database_init.proto

package database_init

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DatabaseInitServiceClient is the client API for DatabaseInitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatabaseInitServiceClient interface {
	InitDatabase(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
}

type databaseInitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseInitServiceClient(cc grpc.ClientConnInterface) DatabaseInitServiceClient {
	return &databaseInitServiceClient{cc}
}

func (c *databaseInitServiceClient) InitDatabase(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, "/database_init.DatabaseInitService/InitDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseInitServiceServer is the server API for DatabaseInitService service.
// All implementations must embed UnimplementedDatabaseInitServiceServer
// for forward compatibility
type DatabaseInitServiceServer interface {
	InitDatabase(context.Context, *InitRequest) (*InitResponse, error)
	mustEmbedUnimplementedDatabaseInitServiceServer()
}

// UnimplementedDatabaseInitServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDatabaseInitServiceServer struct {
}

func (UnimplementedDatabaseInitServiceServer) InitDatabase(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDatabase not implemented")
}
func (UnimplementedDatabaseInitServiceServer) mustEmbedUnimplementedDatabaseInitServiceServer() {}

// UnsafeDatabaseInitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseInitServiceServer will
// result in compilation errors.
type UnsafeDatabaseInitServiceServer interface {
	mustEmbedUnimplementedDatabaseInitServiceServer()
}

func RegisterDatabaseInitServiceServer(s grpc.ServiceRegistrar, srv DatabaseInitServiceServer) {
	s.RegisterService(&DatabaseInitService_ServiceDesc, srv)
}

func _DatabaseInitService_InitDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseInitServiceServer).InitDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/database_init.DatabaseInitService/InitDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseInitServiceServer).InitDatabase(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseInitService_ServiceDesc is the grpc.ServiceDesc for DatabaseInitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseInitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "database_init.DatabaseInitService",
	HandlerType: (*DatabaseInitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitDatabase",
			Handler:    _DatabaseInitService_InitDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "database_init/database_init.proto",
}
