app:
  env: "dev"
  port: "50052"
  log_level: "debug"
  service_name: "database_init_service"

database:
  url: "postgres://user:password@localhost:5432/dbname?sslmode=disable"
  migrations_path: "./deploy/migrations"
