receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 5s
    send_batch_size: 10000

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: app_metrics
    const_labels:
      service: "hello_service"
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  zipkin:
    endpoint: "http://jaeger:9411/api/v2/spans"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp, zipkin]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
