receivers:
    otlp:
        protocols:
            grpc:
                endpoint: "0.0.0.0:4317"
            http:
                endpoint: "0.0.0.0:4318"

processors:
    batch:
        timeout: 5s
        send_batch_size: 10000

exporters:
    debug:
        verbosity: detailed
    prometheus:
        endpoint: "otel-collector:8889" # Endpoint для Prometheus
        namespace: app_metrics
        const_labels:
            service: "hello_service"
    otlp:
        endpoint: "otel-collector:4317"
        tls:
            insecure: true

service:
    pipelines:
        metrics:
            receivers: [ otlp ]
            processors: [ batch ]
            exporters: [ debug, prometheus ]
        traces:
            receivers: [ otlp ]
            processors: [ batch ]
            exporters: [ debug, otlp ]
        logs:
            receivers: [ otlp ]
            processors: [ batch ]
            exporters: [ debug ]
